app = "iphone-culture"
primary_region = "gru"  # Sao Paulo, Brasil (mas cercano a Argentina)

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "3001"
  NODE_ENV = "production"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[mounts]]
  source = "iphone_culture_data"
  destination = "/app/data"
